(function() {
  var script = document.createElement('script');
  script.async = true;
  script.src = 'https://widget.kapa.ai/kapa-widget.bundle.js';
  script.setAttribute('data-website-id', 'c939d944-e3f7-455e-9576-9707174fda5d');
  script.setAttribute('data-project-name', 'ShardingSphere-Widget');
  script.setAttribute('data-project-logo', 'https://shardingsphere.apache.org/images/base/logo.png');
  script.setAttribute('data-button-hide', 'false');
  script.setAttribute('data-bot-protection-mechanism', 'hcaptcha');
  script.setAttribute('data-modal-open-on-command-k', 'true');
  script.setAttribute('data-modal-title', 'Apache ShardingSphere AI');
  script.setAttribute('data-consent-required', 'true');
  script.setAttribute('data-consent-screen-disclaimer', 'By clicking "I agree, let\'s chat", you consent to the use of the AI assistant in accordance with kapa.ai\'s [Privacy Policy](https://www.kapa.ai/content/privacy-policy). This service uses reCAPTCHA, which requires your consent to Google\'s [Privacy Policy](https://policies.google.com/privacy) and [Terms of Service](https://policies.google.com/terms). By proceeding, you explicitly agree to both kapa.ai\'s and Google\'s privacy policies.');
  script.setAttribute('data-project-color', '#ffffff');
  script.setAttribute('data-submit-query-button-bg-color', '#f68d23');
  script.setAttribute('data-button-text-color', '#FF6A13');
  script.setAttribute('data-button-bg-color', '#ffffff');
  script.setAttribute('data-button-border', '1px solid #FFBC80');
  script.setAttribute('data-button-position-bottom', '32%');
  script.setAttribute('data-button-z-index', '1000');
  script.setAttribute('data-modal-z-index', '3000');
  script.setAttribute('data-deep-thinking-button-active-bg-color', '#f68d23');
  script.setAttribute('data-deep-thinking-button-active-hover-bg-color', '#f28314');
  document.head.appendChild(script);
})();
