apiVersion: v1
entries:
  shardingsphere-proxy:
  - apiVersion: v2
    appVersion: 5.1.1
    created: "2022-04-01T19:52:43.673717727+08:00"
    dependencies:
    - condition: mysql.enabled
      name: mysql
      repository: file://./charts/mysql
      version: 1.x.x
    - condition: zookeeper.enabled
      name: zookeeper
      repository: file://./charts/zookeeper
      version: 1.x.x
    digest: a085c70c8df06d8c49df5bc007346ed8c7014ddde3aae61c193aa9d72729c713
    maintainers:
    - name: windghoul
    name: shardingsphere-proxy
    urls:
    - https://shardingsphere.apache.org/charts/shardingsphere-proxy-1.0.0.tgz
    version: 1.0.0
generated: "2022-04-01T19:52:43.673057688+08:00"
