name: Build maven report
on:
  push:
    branches: [ asf-site ]
  pull_request:
  schedule:
  - cron: '0 */3 * * *'
  workflow_dispatch:  

jobs:
  build:
    name: Build maven report
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build Maven site and stage
      run: |
        sh .github/scripts/build-maven-report.sh `pwd`
